### ISSUE TITLE
some confusion about this experiment

### ISSUE THREAD

**Issue by Afleve** [mashijie1028/ActiveGCD#2]
I have looked at the experimental code in detail and have the following confusion:
1.Why is it necessary to initialize model parameters on SimGCD? SimGCD contains more labeled samples (50% of Old) than AGCD in this paper (20% of Old). Doesn't this initialization method allow the model to learn labeled samples that appear in SimGCD but not in AGCD?
2. Why does this experiment need to decouple the originalDataset and SelectedDataset for training? I have observed other ActiveLearning methods and found that decoupling training is rare. In the replication experiment, it was indeed found that decoupling training would cause a sudden decrease in test results. Although the results in the paper can be replicated, I am still confused about this.

**Comment by mashijie1028** [comment]
Hi, thanks for your questions. I will respond point by point.

1. Actually, the model is initialized with the model trained with 20% of the Old, rather than 50%, so it is consistent with our paper. I noticed that in the README file, we set `--prop_train_labels` to 0.5 for the train base model, but it is actually 0.2. I will correct this. Thank you for pointing it out. It does not change the results, just the typo in `README.md` :joy:

   Plus, please see [L93](https://github.com/mashijie1028/ActiveGCD/blob/main/train_al_ema.py#L93) of `train_al_ema.py`, when loading the checkpoints from the base model, we have to specify the args `args.prop_train_labels`. The model checkpoints can only be correctly imported when the parameter `--prop_train_labels` is consistent between the two files `train_base.py` and `train_al_ema.py`. The folder name of base model checkpoints is like `old50_ratio0.2_20231010-081653` for CIFAR100.

2. Good question :+1:. The initial motivation for decoupling is that we found that in AGCD, it is more important to enhance the effect of the selected data. To be more specific, we could strategically set training hyperparameters for the selected data. For example, we empirically found that a smaller batch size (e.g., 8 or 16) of the selected data is more suitable in AGCD. If we set the same batch size of original data (i.e., 128), the effectiveness of active learning could be largely diminished.

   The core difference between AL and AGCD is that there is no labeled data for new classes in  AGCD, while for AL, there are initially plenty of labeled samples for all classes. As a result, in AGCD, we have to enlarge the effect of selected labeled samples for new classes to balance with the old classes as much as possible. Besides, there are unsupervised learning objectives in AGCD, which might also diminish the effect of selected data.

   In this work, decoupling the dataset is our solution considering the empirical results. Future works could also explore other possibilities in the training pipeline and dataset splits. By the way, if the training hyperparameters of the original and selected datasets are exactly the same, decoupled training equals the scenarios of conventional AL.

**Comment by Afleve** [comment]
Thanks for ur response! Now I actually get it.
